paths:
  input_files: "input_files/"
  models: "models/"
  dataset: "dataset/"
  output_files: "output_files/"
models:
  encoder: "roberta-base"
  decoder: "t5-base"
hyperparameters:
  learning_rate: 0.0001
  num_epochs: 10
  batch_size: 16
rl:
  reward_correct: 1.0
  reward_incorrect: -1.0